name = "IJuliaTimeMachine"
uuid = "b814eec1-6f43-4d1d-9289-368939f75c8a"
authors = ["Daniel Spielman <daniel.spielman@yale.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
